### ISSUE TITLE
Successful Login Throws: KeyError: 'attributes'

### ISSUE THREAD

**Issue by smashedr** [etianen/django-python3-ldap#48]
I am getting a KeyError in ldap.py on a successful login in the dictionary `user_data`:

```
INFO:ldap3:ldap3 library initialized - logging emitted with loglevel set to DEBUG - available detail levels are: OFF, ERROR, BASIC, PROTOCOL, NETWORK, EXTENDED - sensitive data will be hidden
ERROR:django.request:Internal Server Error: /autnenticate/
Traceback (most recent call last):
  File "/websites/rnt/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/websites/rnt/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/websites/rnt/home/views.py", line 43, in autnenticate
    userauth = authenticate(username=_ad_user, password=_ad_pass)
  File "/websites/rnt/venv/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/websites/rnt/venv/lib/python3.5/site-packages/django_python3_ldap/auth.py", line 23, in authenticate
    return ldap.authenticate(*args, **kwargs)
  File "/websites/rnt/venv/lib/python3.5/site-packages/django_python3_ldap/ldap.py", line 157, in authenticate
    return c.get_user(**kwargs)
  File "/websites/rnt/venv/lib/python3.5/site-packages/django_python3_ldap/ldap.py", line 101, in get_user
    return self._get_or_create_user(self._connection.response[0])
  File "/websites/rnt/venv/lib/python3.5/site-packages/django_python3_ldap/ldap.py", line 41, in _get_or_create_user
    attributes = user_data["attributes"]
KeyError: 'attributes'
```

`user_data`:

```
INFO:ldap3:ldap3 library initialized - logging emitted with loglevel set to DEBUG - available detail levels are: OFF, ERROR, BASIC, PROTOCOL, NETWORK, EXTENDED - sensitive data will be hidden
INFO:root:<class 'dict'>
INFO:root:['__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
INFO:root:{'uri': ["b'ldaps://ForestDnsZones.domain.com/DC=ForestDnsZones,DC=domain,DC=com'"], 'type': 'searchResRef'}
```

The full configuration:

```
AUTHENTICATION_BACKENDS = (
        'django_python3_ldap.auth.LDAPBackend',
)
LDAP_AUTH_URL = "ldaps://domain.com"
LDAP_AUTH_USE_TLS = True
LDAP_AUTH_SEARCH_BASE = "dc=domain,dc=com"
LDAP_AUTH_OBJECT_CLASS = "userClass"
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "DOMAIN"
LDAP_AUTH_CONNECTION_USERNAME = 'user'
LDAP_AUTH_CONNECTION_PASSWORD = 'pass'
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "loggers": {
        "django_python3_ldap": {
            "level": "DEBUG",
        },
    },
}
```

**Comment by etianen** [comment]
Hrm...

Could you add a print(user_data) before line 41 of that file. I'm curious why your AD server isn't returning any data...

**Comment by smashedr** [comment]
As mentioned above, I believe this is the user_data you are asking about:

```
{'uri': ["b'ldaps://ForestDnsZones.domain.com/DC=ForestDnsZones,DC=domain,DC=com'"], 'type': 'searchResRef'}
```

**Comment by etianen** [comment]
Oops, missed that. Sorry!

I've just pushed a commit to master that might solve your issue. Let me know how it goes!

**Comment by smashedr** [comment]
Still throws the same error, and user_data contains the same content.

**Comment by etianen** [comment]
Damn.

I'm afraid I can't replicate your test setup, as I don't have access to an ActiveDirectory server, let alone two of them. I can debug further if you give me access to your server, or you can do further investigation yourself.

I'm basically convinced it's due to an LDAP referral, which `ldap3` is supposed to handle automatically. Something to investigate:

Are there other search results returned by the server containing the actual data? Potentially the referral record is left in there, and needs to be ignored by django-python3-ldap.

**Comment by smills2929** [comment]
I am getting the same key error, except for an unsuccessful login. When no user is found that matches the search Django returns a 500 error:
File "/Users/Smills/.virtualenvs/api/lib/python2.7/site-packages/django_python3_ldap/ldap.py", line 41, in _get_or_create_user
    attributes = user_data["attributes"]

**Comment by smills2929** [comment]
From the looks of it, the ldap connection search result (`self._connection.search`) in Connection.get_user contains multiple {type': 'searchResRef'} dicts, but nothing else. It then references the first searchResRef object when calling `_get_or_create_user`, but this object does not have attributes available. Perhaps auth should fail if no attributes exist?

This is with an Active Directory server.

**Comment by etianen** [comment]
That would definitely be better than a server error.

Could you knock together a pull request? I'm not able to fully test the behaviour on AD, since my own test server os OpenLDAP.

**Comment by smills2929** [comment]
No worries, I'll look into it.

**Comment by smills2929** [comment]
Handles no attributes as unsuccessful login: https://github.com/etianen/django-python3-ldap/pull/49

**Comment by schmitgreg** [comment]
I will give you access to a Windows Server 2012 if you want to play around. I am getting this for user_data:

user_data	
{'type': 'searchResRef',
 'uri': ["b'ldap://ForestDnsZones.labcorp.domain.com/DC=ForestDnsZones,DC=labcorp,DC=domain,DC=com'"]}

I really dislike Windows but in my current environment we have to work with an existing AD. I got a successful config for another server running openLDAP, but Windows appears to not be returning any attributes and I don't know enough about Windows Server to figure out why.

-gns

**Comment by smills2929** [comment]
That is the result you'd get if your search filters the user you're looking for out. Perhaps you have a valid username, and a group filter for a group that doesn't exist?

**Comment by schmitgreg** [comment]
I didn't think I used search filters, but my search base was not very specific so I honed it in. Before it was just "dc=labcorp,dc=domain,dc=com" and I changed it to "ou=company1,ou=customers,dc=labcorp,dc=domain,dc=com". In both scenarios I got successful logins at the server from the event logs.

Now the behavior is that I no longer get the django system error but I do get a 'Please enter a correct username and password' return error. It is so weird because in Server 2012 I see 'Audit Success'.

**Comment by smills2929** [comment]
Hmm, that is odd, I can't say I am sure what's happening there.

Also, have you had a chance to look at the pull request @etianen ?

**Comment by etianen** [comment]
Sorry for the lack of communication, I've been snowed under.

I've reviewed #49 now, and should be able to merge it with the suggested changes.
