### ISSUE TITLE
LDAP3 error

### ISSUE THREAD

**Issue by amarvin** [etianen/django-python3-ldap#58]
I tried adding django-python3-ldap to one of my Django projects. The project runs and displays the login page, but I get the following error when I try logging in with my credentials:

  File "...\env\lib\site-packages\django_python3_ldap\ldap.py", line 162, in authenticate
    return c.get_user(**kwargs)
  File "...\AppData\Local\Continuum\Anaconda3\lib\contextlib.py", line 78, in __exit__
    raise RuntimeError("generator didn't stop after throw()")

Running Django in debug mode, I can see the local variables within ldap.py's authenticate function at line 137 of ldap.py:

- auto_bind = 'NO_TLS'
- c = Connection(server=Server(host='_HOSTNAME_', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], get_info='NO_INFO'), user='_DOMAIN_\\_USERNAME_', password='_PASSWORD_', auto_bind='NO_TLS', version=3, authentication='SIMPLE', client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=False, lazy=False, raise_exceptions=False, **fast_decoder=TrueFalse**)
- ex = LDAPSocketOpenError('invalid server address',)
- kwargs = {'username': '_USERNAME_'}
- password = _PASSWORD_
- username = '_DOMAIN_\\_USERNAME_'

where the italics are replaced with my real Active Directory and user credentials. I can run the same ldap command without Django just from Python 3.5 and get an error "TrueFalse" is not defined from the bolded section above. If I change that to just "True", the connection is bind-able.

Is this a problem in django-python3-ldap or in the ldap library? I can't even see where the fast_decorder=TrueFalse comes from, but believe this is the reason for my LDAP authentication fails when trying to sign into my Django app.

**Comment by amarvin** [comment]
Looks like the ldap3 package is the one creating the "TrueFalse". I traced it back to 
\ldap3\core\connection.py
lines 351-352 (or) lines 385-386 where the string "False" is appended to the Connection command, if the attributes receive_timeout or return_empty_attributes are empty.

I made a change to 
django_python3_ldap\ldap.py
line 136 by adding default settings
- receive_timeout=True
- return_empty_attributes=True

and restarted the Django server, but I still get the same error when trying to login, although the Connection command now looks okay.

**Comment by amarvin** [comment]
It seems this problem is more about ldap3, rather than django-python3-ldap

**Comment by etianen** [comment]
What version of ldap3 are you using? They may have released a bad version.

**Comment by amarvin** [comment]
I'm using ldap3 version 1.4.0

**Comment by etianen** [comment]
A possible fix is in the master branch. Please take a look.

**Comment by amarvin** [comment]
Thanks for your help. I pulled your update, but still get an error on line 142 of \django_python3_ldap\ldap.py. The exception displayed by Django is RuntimeError "generator didn't stop after throw()" and traceback shows the local variables were:

auto_bind = 'NO_TLS'
c = Connection(server=Server(host='HOST', port=PORT, use_ssl=False, allowed_referral_hosts=[('*', True)], get_info='SCHEMA'), user='DOMAIN\\USERNAME', password='PASSWORD', auto_bind='NO_TLS', version=3, authentication='SIMPLE', client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=False, lazy=False, raise_exceptions=True, fast_decoder=True, auto_range=True, return_empty_attributes=True)
ex = LDAPSocketOpenError('invalid server address',)
kwargs = {'username': 'USERNAME'}
password = 'PASSWORD'
username 'DOMAND\\USERNAME'

What's interesting is that if I open the Python interactive shell, import ldap3 and run that "c = ..." line above, c.bind() returns True. Doesn't this mean that the LDAP connection via ldap3 to the server with my USERNAME and PASSWORD works? Django-python3-ldap is using something more sophisticated besides "c.bind()" to confirm the user credentials though in \ldap.py Connection.get_user and authenticate

**Comment by amarvin** [comment]
Actually, now I see that in
django_python3_ldap\ldap.Connection.get_user
you use connection.search(...) to grab ldap info and confirm the authorization and grab related user information for Django, rather than simply connection.bind(). I might need to fix some settings, like the LDAP_AUTH_SEARCH_BASE with help from someone that knows my company's AD.

**Comment by etianen** [comment]
I'd be very interested to see a minimal setup to reproduce the `generator didn't stop after throw` error. That sounds really wrong, but I can't reproduce it.

**Comment by etianen** [comment]
The RuntimeError is now fixed in master.

**Comment by george-silva** [comment]
I'm still getting this error.

I'm using the latest LDAP3 version with the latest pyasn1
